name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Debug PHPUnit Directory
        run: ls -R vendor/phpunit/phpunit/src/

      - name: Run PHPUnit Tests
        run: ./vendor/bin/phpunit tests