name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Install Dependencies
      run: composer install --no-scripts --prefer-dist

    - name: Verify Installed Dependencies
      run: composer show

    - name: List Vendor Directory
      run: ls -al ./vendor/bin

    - name: Run Tests
      run: ./vendor/bin/phpunit tests